[package]
name = "star"
version = "0.1.0"
edition = "2024"

[dependencies]
oqs = "0.11.0"
aes = "0.8.4"
block-modes = "0.9.1"
block-padding = "0.4.2"
rand = "0.9.2"
sha3 = "0.10.8"
thiserror = "2.0.3"
pkcs7 = "0.4.1"
